language: c

# TODO: Support Python 2.7 too
python:
  - "3.6"

install:
  - chmod -R u+x scripts
  - python3 scripts/install_deps.py # TODO: Should not depend on Python version

before_script:
  - source scripts/set_watcom.sh

script:
  - wmake
