name: Build

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          chmod -R u+x scripts
          python scripts/install_deps.py
      - name: Build library (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          source scripts/set_watcom.sh
          wmake
      - name: Build library (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd  # TODO: Add support for PowerShell
        run: scripts\set_watcom.bat && wmake