name: Build

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

# At the time of writing, there's unfortunately no matrix feature for running
# across multiple shells in one OS.
jobs:
  build_bash:
    name: Build (Linux bash)
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          chmod -R u+x scripts
          python scripts/install_deps.py
      - name: Build library (Linux bash)
        run: |
          source scripts/set_watcom.sh
          wmake

  build_cmd:
    name: Build (Windows CMD)
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: python scripts\install_deps.py
      - name: Build library (Windows CMD)
        shell: cmd
        run: scripts\set_watcom.bat && wmake

  build_powershell:
    name: Build (Windows Powershell)
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: python scripts\install_deps.py
      - name: Build library (Windows Powershell)
        shell: powershell
        run: Unblock-File -Path scripts\set_watcom.ps1; scripts\set_watcom.ps1; wmake